server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12354917"
    username: sql12354917
    password: jVCB9AYRbm
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
app:
  authorization:
    header:
      name: Authorization
      prefix: Bearer
  jwt-token:
    tokenSecret: Toeic
    expiration: 604800000
