server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/elearning"
    username: root
    password: root
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
app:
  authorization:
    header:
      name: Authorization
      prefix: Bearer
  jwt-token:
    tokenSecret: Toeic
    expiration: 604800000
